-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 13:43:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_service` DEFAULT CHARACTER SET utf8 ;
USE `car_service` ;

-- -----------------------------------------------------
-- Table `car_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_service`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_service`.`status_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_service`.`status_car` (
  `idStatusCar` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '\'available\', \'unavailable\'\'',
  PRIMARY KEY (`idStatusCar`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_service`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_service`.`car` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `productionYear` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL COMMENT 'price per day',
  `idStatusCar` INT NOT NULL,
  `minDays` INT NULL,
  `maxDays` INT NULL,
  PRIMARY KEY (`idCar`),
  INDEX `car-status_idx` (`idStatusCar` ASC) VISIBLE,
  CONSTRAINT `car-status`
    FOREIGN KEY (`idStatusCar`)
    REFERENCES `car_service`.`status_car` (`idStatusCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_service`.`status_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_service`.`status_reservation` (
  `idStatusReserv` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'placed, confirmed, canceled',
  PRIMARY KEY (`idStatusReserv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_service`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_service`.`reservation` (
  `idReservation` INT NULL,
  `idUser` INT NOT NULL,
  `idCar` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `sum` DECIMAL(10,2) NOT NULL COMMENT 'total sum\n',
  `idStatusReserv` INT NOT NULL,
  PRIMARY KEY (`idReservation`),
  INDEX `reservation-user_idx` (`idUser` ASC) VISIBLE,
  INDEX `reservation-car_idx` (`idCar` ASC) VISIBLE,
  INDEX `reservation-status_idx` (`idStatusReserv` ASC) VISIBLE,
  CONSTRAINT `reservation-user`
    FOREIGN KEY (`idUser`)
    REFERENCES `car_service`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reservation-car`
    FOREIGN KEY (`idCar`)
    REFERENCES `car_service`.`car` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reservation-status`
    FOREIGN KEY (`idStatusReserv`)
    REFERENCES `car_service`.`status_reservation` (`idStatusReserv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
