"""First3

Revision ID: daab91331425
Revises: 
Create Date: 2021-12-02 23:51:10.571365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daab91331425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_car',
    sa.Column('idStatusCar', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatusCar'),
    sa.UniqueConstraint('idStatusCar')
    )
    op.create_table('status_reservation',
    sa.Column('idStatusReserv', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatusReserv'),
    sa.UniqueConstraint('idStatusReserv')
    )
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('login', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=75), nullable=False),
    sa.Column('user_status', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('idUser'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('car',
    sa.Column('idCar', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('productionYear', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('minDays', sa.Integer(), nullable=True),
    sa.Column('maxDays', sa.Integer(), nullable=True),
    sa.Column('idStatusCar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatusCar'], ['status_car.idStatusCar'], ),
    sa.PrimaryKeyConstraint('idCar'),
    sa.UniqueConstraint('idCar')
    )
    op.create_table('reservation',
    sa.Column('idReservation', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('sum', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idCar', sa.Integer(), nullable=True),
    sa.Column('idStatusReserv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCar'], ['car.idCar'], ),
    sa.ForeignKeyConstraint(['idStatusReserv'], ['status_reservation.idStatusReserv'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idUser'], ),
    sa.PrimaryKeyConstraint('idReservation'),
    sa.UniqueConstraint('idReservation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('car')
    op.drop_table('user')
    op.drop_table('status_reservation')
    op.drop_table('status_car')
    # ### end Alembic commands ###
